<?php

/**
 * This is the model base class for the table "subs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Subs".
 *
 * Columns in table "subs" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $mail
 *
 */
abstract class BaseSubs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'subs';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Subs|Subs', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('mail','email','message'=>'не является правильным E-Mail адресом'),
			array('name, mail', 'required','message'=> 'Заполните поле'),
			array('name, mail', 'length', 'max'=>255),
			array('id, name, mail', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'mail' => Yii::t('app', 'Mail'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('mail', $this->mail, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}