<?php

/**
 * This is the model base class for the table "comment_events".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CommentEvents".
 *
 * Columns in table "comment_events" available as properties of the model,
 * followed by relations of table "comment_events" available as properties of the model.
 *
 * @property integer $id
 * @property integer $events_id
 * @property integer $author_id
 * @property string $date
 * @property string $comment
 *
 * @property Events $events
 * @property Users $author
 * @property CommentEventsAnswer[] $commentEventsAnswers
 */
abstract class BaseCommentEvents extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comment_events';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CommentEvents|CommentEvents', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('events_id, author_id, date, comment', 'required'),
			array('events_id, author_id', 'numerical', 'integerOnly'=>true),
			array('date', 'length', 'max'=>255),
			array('id, events_id, author_id, date, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'events' => array(self::BELONGS_TO, 'Events', 'events_id'),
			'author' => array(self::BELONGS_TO, 'Users', 'author_id'),
			'commentEventsAnswers' => array(self::HAS_MANY, 'CommentEventsAnswer', 'comment_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'events_id' => null,
			'author_id' => null,
			'date' => Yii::t('app', 'Date'),
			'comment' => Yii::t('app', 'Comment'),
			'events' => null,
			'author' => null,
			'commentEventsAnswers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('events_id', $this->events_id);
		$criteria->compare('author_id', $this->author_id);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('comment', $this->comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}