<?php

/**
 * This is the model base class for the table "menu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Menu".
 *
 * Columns in table "menu" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $img_url
 * @property integer $position
 * @property string $title
 * @property string $url
 * @property string $location
 * @property integer $active
 *
 */
abstract class BaseMenu extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'menu';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Menu|Menus', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('position, title, url, location', 'required'),
			array('position, active', 'numerical', 'integerOnly'=>true),
			array('img_url, title, url, location', 'length', 'max'=>255),
			array('img_url, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, img_url, position, title, url, location, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'img_url' => Yii::t('app', 'Img Url'),
			'position' => Yii::t('app', 'Position'),
			'title' => Yii::t('app', 'Title'),
			'url' => Yii::t('app', 'Url'),
			'location' => Yii::t('app', 'Location'),
			'active' => Yii::t('app', 'Active'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('img_url', $this->img_url, true);
		$criteria->compare('position', $this->position);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('location', $this->location, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}