<?php

/**
 * This is the model base class for the table "banner_stat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BannerStat".
 *
 * Columns in table "banner_stat" available as properties of the model,
 * followed by relations of table "banner_stat" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_banner
 * @property integer $data
 *
 * @property Banner $idBanner
 */
abstract class BaseBannerStat extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banner_stat';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BannerStat|BannerStats', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_banner, data', 'required'),
			array('id_banner, data', 'numerical', 'integerOnly'=>true),
			array('id, id_banner, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idBanner' => array(self::BELONGS_TO, 'Banner', 'id_banner'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_banner' => null,
			'data' => Yii::t('app', 'Data'),
			'idBanner' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_banner', $this->id_banner);
		$criteria->compare('data', $this->data);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}