<?php

/**
 * This is the model base class for the table "comment_catalog".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CommentCatalog".
 *
 * Columns in table "comment_catalog" available as properties of the model,
 * followed by relations of table "comment_catalog" available as properties of the model.
 *
 * @property integer $id
 * @property integer $catalog_id
 * @property integer $author_id
 * @property string $date
 * @property string $comment
 *
 * @property CommentAnswer[] $commentAnswers
 * @property Users $author
 * @property Catalog $catalog
 */
abstract class BaseCommentCatalog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comment_catalog';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CommentCatalog|CommentCatalogs', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('catalog_id, author_id, date, comment', 'required'),
			array('catalog_id, author_id', 'numerical', 'integerOnly'=>true),
			array('date', 'length', 'max'=>255),
			array('id, catalog_id, author_id, date, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'commentAnswers' => array(self::HAS_MANY, 'CommentAnswer', 'id_comment', 'order'=>'date ASC'),
			'author' => array(self::BELONGS_TO, 'Users', 'author_id'),
			'catalog' => array(self::BELONGS_TO, 'Catalog', 'catalog_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'catalog_id' => null,
			'author_id' => null,
			'date' => Yii::t('app', 'Date'),
			'comment' => Yii::t('app', 'Comment'),
			'commentAnswers' => null,
			'author' => null,
			'catalog' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('catalog_id', $this->catalog_id);
		$criteria->compare('author_id', $this->author_id);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('comment', $this->comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}