<?php

/**
 * This is the model base class for the table "jobs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Jobs".
 *
 * Columns in table "jobs" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property integer $isVisible
 *
 */
abstract class BaseJobs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'jobs';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Jobs|Jobs', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('isVisible', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('body', 'safe'),
			array('name, body, isVisible', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, body, isVisible', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'body' => Yii::t('app', 'Body'),
			'isVisible' => Yii::t('app', 'Is Visible'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('body', $this->body, true);
		$criteria->compare('isVisible', $this->isVisible);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}