<?php

/**
 * This is the model base class for the table "seo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Seo".
 *
 * Columns in table "seo" available as properties of the model,
 * followed by relations of table "seo" available as properties of the model.
 *
 * @property integer $id
 * @property string $page
 * @property integer $id_article
 * @property integer $id_debats
 * @property integer $id_events
 * @property string $description
 * @property string $keywords
 * @property string $title
 *
 * @property Catalog $idArticle
 * @property Debats $idDebats
 * @property Events $idEvents
 */
abstract class BaseSeo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'seo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Seo|Seos', $n);
	}

	public static function representingColumn() {
		return 'page';
	}

	public function rules() {
		return array(
			array('id_article, id_debats, id_events', 'numerical', 'integerOnly'=>true),
			array('page', 'length', 'max'=>255),
			array('description, keywords, title', 'length', 'max'=>500),
			array('page, id_article, id_debats, id_events, description, keywords, title', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, page, id_article, id_debats, id_events, description, keywords, title', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idArticle' => array(self::BELONGS_TO, 'Catalog', 'id_article'),
			'idDebats' => array(self::BELONGS_TO, 'Debats', 'id_debats'),
			'idEvents' => array(self::BELONGS_TO, 'Events', 'id_events'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'page' => Yii::t('app', 'Page'),
			'id_article' => null,
			'id_debats' => null,
			'id_events' => null,
			'description' => Yii::t('app', 'Description'),
			'keywords' => Yii::t('app', 'Keywords'),
			'title' => Yii::t('app', 'Title'),
			'idArticle' => null,
			'idDebats' => null,
			'idEvents' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('page', $this->page, true);
		$criteria->compare('id_article', $this->id_article);
		$criteria->compare('id_debats', $this->id_debats);
		$criteria->compare('id_events', $this->id_events);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('keywords', $this->keywords, true);
		$criteria->compare('title', $this->title, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}