<?php

/**
 * This is the model base class for the table "banner".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Banner".
 *
 * Columns in table "banner" available as properties of the model,
 * followed by relations of table "banner" available as properties of the model.
 *
 * @property integer $id
 * @property string $position
 * @property string $url
 * @property string $img
 * @property string $date_start
 * @property string $date_end
 *
 * @property BannerStat[] $bannerStats
 */
abstract class BaseBanner extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banner';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Banner|Banners', $n);
	}

	public static function representingColumn() {
		return 'position';
	}

	public function rules() {
		return array(
			array('position, url, img, date_start, date_end', 'required'),
			array('position, url, img, date_start, date_end', 'length', 'max'=>255),
			array('id, position, url, img, date_start, date_end', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bannerStats' => array(self::HAS_MANY, 'BannerStat', 'id_banner'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'position' => Yii::t('app', 'Position'),
			'url' => Yii::t('app', 'Url'),
			'img' => Yii::t('app', 'Img'),
			'date_start' => Yii::t('app', 'Date Start'),
			'date_end' => Yii::t('app', 'Date End'),
			'bannerStats' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('position', $this->position, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('img', $this->img, true);
		$criteria->compare('date_start', $this->date_start, true);
		$criteria->compare('date_end', $this->date_end, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}