<?php

/**
 * This is the model base class for the table "favorites".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Favorites".
 *
 * Columns in table "favorites" available as properties of the model,
 * followed by relations of table "favorites" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_article
 * @property integer $id_user
 *
 * @property Catalog $idArticle
 * @property Users $idUser
 */
abstract class BaseFavorites extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'favorites';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Favorites|Favorites', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_article, id_user', 'required'),
			array('id_article, id_user', 'numerical', 'integerOnly'=>true),
			array('id, id_article, id_user', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idArticle' => array(self::BELONGS_TO, 'Catalog', 'id_article'),
			'idUser' => array(self::BELONGS_TO, 'Users', 'id_user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_article' => null,
			'id_user' => null,
			'idArticle' => null,
			'idUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_article', $this->id_article);
		$criteria->compare('id_user', $this->id_user);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}