<?php

/**
 * This is the model base class for the table "theme_webinar".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ThemeWebinar".
 *
 * Columns in table "theme_webinar" available as properties of the model,
 * followed by relations of table "theme_webinar" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 *
 * @property Webinar[] $webinars
 */
abstract class BaseThemeWebinar extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'theme_webinar';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ThemeWebinar|ThemeWebinars', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('title', 'length', 'max'=>255),
			array('id, title', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'webinars' => array(self::HAS_MANY, 'Webinar', 'id_theme'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'webinars' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}