<?php

/**
 * This is the model base class for the table "connect_webinar".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ConnectWebinar".
 *
 * Columns in table "connect_webinar" available as properties of the model,
 * followed by relations of table "connect_webinar" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_webinar
 * @property integer $id_pred
 *
 * @property Users $idPred
 * @property Webinar $idWebinar
 */
abstract class BaseConnectWebinar extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'connect_webinar';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ConnectWebinar|ConnectWebinars', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_webinar, id_pred', 'required'),
			array('id_webinar, id_pred', 'numerical', 'integerOnly'=>true),
			array('id, id_webinar, id_pred', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPred' => array(self::BELONGS_TO, 'Users', 'id_pred'),
			'idWebinar' => array(self::BELONGS_TO, 'Webinar', 'id_webinar'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_webinar' => null,
			'id_pred' => null,
			'idPred' => null,
			'idWebinar' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_webinar', $this->id_webinar);
		$criteria->compare('id_pred', $this->id_pred);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}