<?php

/**
 * This is the model base class for the table "events_main".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventsMain".
 *
 * Columns in table "events_main" available as properties of the model,
 * followed by relations of table "events_main" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $events_id
 *
 * @property Events $events
 * @property Users $user
 */
abstract class BaseEventsMain extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'events_main';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EventsMain|EventsMains', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user_id, events_id', 'required'),
			array('user_id, events_id', 'numerical', 'integerOnly'=>true),
			array('id, user_id, events_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'events' => array(self::BELONGS_TO, 'Events', 'events_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'events_id' => null,
			'events' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('events_id', $this->events_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}