<?php

/**
 * This is the model base class for the table "connect_debat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ConnectDebat".
 *
 * Columns in table "connect_debat" available as properties of the model,
 * followed by relations of table "connect_debat" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_debat
 * @property integer $id_user
 *
 * @property Users $idUser
 * @property Debats $idDebat
 */
abstract class BaseConnectDebat extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'connect_debat';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ConnectDebat|ConnectDebats', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_debat, id_user', 'required'),
			array('id_debat, id_user', 'numerical', 'integerOnly'=>true),
			array('id, id_debat, id_user', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUser' => array(self::BELONGS_TO, 'Users', 'id_user'),
			'idDebat' => array(self::BELONGS_TO, 'Debats', 'id_debat'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_debat' => null,
			'id_user' => null,
			'idUser' => null,
			'idDebat' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_debat', $this->id_debat);
		$criteria->compare('id_user', $this->id_user);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}