<?php

/**
 * This is the model base class for the table "question_theme".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QuestionTheme".
 *
 * Columns in table "question_theme" available as properties of the model,
 * followed by relations of table "question_theme" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Question[] $questions
 * @property QuestionThemeExpert[] $questionThemeExperts
 */
abstract class BaseQuestionTheme extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'question_theme';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QuestionTheme|QuestionThemes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>255),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'questions' => array(self::HAS_MANY, 'Question', 'id_theme'),
			'questionThemeExperts' => array(self::HAS_MANY, 'QuestionThemeExpert', 'id_theme'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'questions' => null,
			'questionThemeExperts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}