<?php

/**
 * This is the model base class for the table "question_theme_expert".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QuestionThemeExpert".
 *
 * Columns in table "question_theme_expert" available as properties of the model,
 * followed by relations of table "question_theme_expert" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_expert
 * @property integer $id_theme
 *
 * @property QuestionTheme $idTheme
 * @property Users $idExpert
 */
abstract class BaseQuestionThemeExpert extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'question_theme_expert';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QuestionThemeExpert|QuestionThemeExperts', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_expert, id_theme', 'required'),
			array('id_expert, id_theme', 'numerical', 'integerOnly'=>true),
			array('id, id_expert, id_theme', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idTheme' => array(self::BELONGS_TO, 'QuestionTheme', 'id_theme'),
			'idExpert' => array(self::BELONGS_TO, 'Users', 'id_expert'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_expert' => null,
			'id_theme' => null,
			'idTheme' => null,
			'idExpert' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_expert', $this->id_expert);
		$criteria->compare('id_theme', $this->id_theme);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}